-- ---------- v15 upgrade (server settings and permission roles) ----------
alter table public.servers add column if not exists description text not null default '';

create table if not exists public.server_roles (
  id bigint generated by default as identity primary key,
  server_id bigint not null references public.servers(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 32),
  color text not null default '#99aab5' check (color ~ '^#[0-9A-Fa-f]{6}$'),
  permissions jsonb not null default '{}'::jsonb check (jsonb_typeof(permissions) = 'object'),
  position integer not null default 0,
  created_at timestamptz not null default now(),
  unique (server_id, name)
);
create table if not exists public.server_member_roles (
  server_id bigint not null references public.servers(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role_id bigint not null references public.server_roles(id) on delete cascade,
  assigned_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (server_id, user_id, role_id)
);
create index if not exists server_member_roles_user_idx on public.server_member_roles(user_id, server_id);
alter table public.server_roles enable row level security;
alter table public.server_member_roles enable row level security;
revoke all on public.server_roles, public.server_member_roles from anon, authenticated;
grant select, insert, update, delete on public.server_roles, public.server_member_roles to authenticated;
grant usage, select on sequence public.server_roles_id_seq to authenticated;

create or replace function public.has_server_permission(p_server_id bigint, p_permission text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select auth.uid() is not null and (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
    or exists (select 1 from public.servers s where s.id = p_server_id and s.created_by = auth.uid())
    or (p_permission <> 'owner_control' and exists (
      select 1 from public.server_member_roles smr
      join public.server_roles sr on sr.id = smr.role_id and sr.server_id = smr.server_id
      where smr.server_id = p_server_id and smr.user_id = auth.uid()
        and (coalesce(sr.permissions ->> 'administrator', 'false') = 'true'
          or coalesce(sr.permissions ->> p_permission, 'false') = 'true')
    ))
  );
$$;
revoke all on function public.has_server_permission(bigint, text) from public, anon;
grant execute on function public.has_server_permission(bigint, text) to authenticated;

drop policy if exists "server roles readable" on public.server_roles;
create policy "server roles readable" on public.server_roles
  for select using (auth.uid() is not null);
drop policy if exists "server role managers create roles" on public.server_roles;
create policy "server role managers create roles" on public.server_roles for insert
  with check (public.has_server_permission(server_id, 'manage_roles')
    and (not coalesce(permissions ->> 'administrator', 'false') = 'true'
      or public.has_server_permission(server_id, 'owner_control')));
drop policy if exists "server role managers edit roles" on public.server_roles;
create policy "server role managers edit roles" on public.server_roles for update
  using (public.has_server_permission(server_id, 'manage_roles'))
  with check (public.has_server_permission(server_id, 'manage_roles')
    and (not coalesce(permissions ->> 'administrator', 'false') = 'true'
      or public.has_server_permission(server_id, 'owner_control')));
drop policy if exists "server role managers delete roles" on public.server_roles;
create policy "server role managers delete roles" on public.server_roles for delete
  using (public.has_server_permission(server_id, 'manage_roles'));

drop policy if exists "server role assignments readable" on public.server_member_roles;
create policy "server role assignments readable" on public.server_member_roles
  for select using (auth.uid() is not null);
drop policy if exists "server role managers assign roles" on public.server_member_roles;
create policy "server role managers assign roles" on public.server_member_roles for insert
  with check (public.has_server_permission(server_id, 'manage_roles')
    and exists (select 1 from public.server_roles sr where sr.id = server_member_roles.role_id and sr.server_id = server_member_roles.server_id
      and (not coalesce(sr.permissions ->> 'administrator', 'false') = 'true'
        or public.has_server_permission(server_member_roles.server_id, 'owner_control'))));
drop policy if exists "server role managers remove roles" on public.server_member_roles;
create policy "server role managers remove roles" on public.server_member_roles for delete
  using (public.has_server_permission(server_id, 'manage_roles'));

drop policy if exists "server managers update settings" on public.servers;
create policy "server managers update settings" on public.servers for update
  using (public.has_server_permission(id, 'manage_server'))
  with check (public.has_server_permission(id, 'manage_server'));

drop policy if exists "managers create channels" on public.channels;
create policy "managers create channels" on public.channels for insert
  with check (public.has_server_permission(server_id, 'manage_channels'));
drop policy if exists "server managers update channels" on public.channels;
create policy "server managers update channels" on public.channels for update
  using (public.has_server_permission(server_id, 'manage_channels'))
  with check (public.has_server_permission(server_id, 'manage_channels'));
drop policy if exists "server managers delete channels" on public.channels;
create policy "server managers delete channels" on public.channels for delete
  using (public.has_server_permission(server_id, 'manage_channels'));

drop policy if exists "mods delete messages" on public.messages;
create policy "mods delete messages" on public.messages for delete using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin', 'mod'))
  or exists (
    select 1 from public.channels c
    where c.id = messages.channel_id and public.has_server_permission(c.server_id, 'manage_messages')
  )
);

create or replace function public.set_message_pin(p_message_id bigint, p_pinned boolean)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target_server bigint;
begin
  select c.server_id into target_server
  from public.messages m join public.channels c on c.id = m.channel_id
  where m.id = p_message_id;
  if target_server is null then raise exception 'Message not found'; end if;
  if not exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin', 'mod'))
    and not public.has_server_permission(target_server, 'manage_messages') then
    raise exception 'You need the Manage Messages permission';
  end if;
  update public.messages set pinned = p_pinned where id = p_message_id;
end;
$$;
revoke all on function public.set_message_pin(bigint, boolean) from public, anon;
grant execute on function public.set_message_pin(bigint, boolean) to authenticated;
